setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

# workaround for Xpra
# set-hook -g pane-set-clipboard "run -b 'if [ ! -z \${DISPLAY+x} ]; then tmux save-buffer - | xclip -i -sel clipboard > /dev/null; fi'"

set -g mouse on
set -g set-clipboard on
set-option -g prefix C-Space
# bind C-Space send-prefix
bind r source-file $HOME/.config/tmux/tmux.conf \; display "Reloaded!"
set -g default-terminal "tmux-256color"
set-option -sga terminal-overrides ",xterm-256color:RGB,st*:Tc"
set -sga terminal-features ",*:hyperlinks"

set -g default-shell $SHELL

set-option -g history-limit 50000
set-option -g display-time 2000
set-option -g focus-events on
set -g status-interval 3

set -g base-index 1

source-file $HOME/.config/tmux/pane.tmux
source-file $HOME/.config/tmux/status.tmux

setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

run-shell $HOME/.config/tmux/pain_control.tmux
